MyswoleMateMvcApp/Models/Trainee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyswoleMateMvcApp.Models
{
    public class Trainee
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int Height { get; set; }
        public int Weight { get; set; }
        public string CellNbr { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
     
    }
}

MyswoleMateMvcApp/Models/TraineeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyswoleMateMvcApp.Models
{
    public class TraineeViewModel
    {
        public int TraineeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int Height { get; set; }
        public int Weight { get; set; }
        public string CellNbr { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public int WorkoutID { get; set; }
        public string DisplayHeight { get; set; }
        public string DisplayCellNbr { get; set; }
        public string DisplayGender
        {
            get
            {
                if (this.Gender == "M")
                    return "Male";
                else if (this.Gender == "F")
                    return "Female";
                else
                    return "Not Specified";
            }
        }
    }
}

MyswoleMateMvcApp/Models/WorkoutViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MySwoleMate.Models
{
    public class WorkoutViewModel
    {
        public int WorkoutID { get; set; }

        public string Name { get; set; }

        public string Excercise1 { get; set; }

        public int Excercise1Reps { get; set; }

        public int Excercise1Sets { get; set; }

        public string DisplayExercise1
        {
            get
            {
                return this.Excercise1 + ": " + this.Excercise1Sets + " x " + this.Excercise1Reps;
            }
        }

        public string Excercise2 { get; set; }

        public int Excercise2Reps { get; set; }

        public int Excercise2Sets { get; set; }

        public string DisplayExercise2
        {
            get
            {
                return this.Excercise2 + ": " + this.Excercise2Sets + " x " + this.Excercise2Reps;
            }
        }

        public string Excercise3 { get; set; }

        public int Excercise3Reps { get; set; }

        public int Excercise3Sets { get; set; }

        public string DisplayExercise3
        {
            get
            {
                return this.Excercise3 + ": " + this.Excercise3Sets + " x " + this.Excercise3Reps;
            }
        }

        public string Excercise4 { get; set; }

        public int Excercise4Reps { get; set; }

        public int Excercise4Sets { get; set; }

        public string DisplayExercise4
        {
            get
            {
                return this.Excercise4 + ": " + this.Excercise4Sets + " x " + this.Excercise4Reps;
            }
        }

        public string Excercise5 { get; set; }

        public int Excercise5Reps { get; set; }

        public int Excercise5Sets { get; set; }

        public string DisplayExercise5
        {
            get
            {
                return this.Excercise5 + ": " + this.Excercise5Sets + " x " + this.Excercise5Reps;
            }
        }
    }
}

MyswoleMateMvcApp/Controllers/TraineeController.cs
using MyswoleMateMvcApp.Models;
using MyswoleMateMvcApp.MySwoleMateDAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyswoleMateMvcApp.Controllers
{
    public class TraineeController : Controller
    {

        TraineeDAL trainee = new TraineeDAL();
        public ActionResult Index()
        {
          
            return View();
        }

        public ActionResult CreateNewTrainee()
        {
            return View();
        }

        public ActionResult CreateNewTraineeInfo(Trainee traineeObj)
        {
            trainee.AddTraineeInfo(traineeObj);
           return RedirectToAction("TraineeList");

        }
        public ActionResult TraineeList()
        {
            
            var trainees = trainee.GetAllTrainees();

            foreach (var item in trainees)
            {
                //for each item take the Height and CellNbr values,
                //use the HeightDisplay and PhoneDisplay methods
                //and store the returned values from the methods
                //into the HeightDisplay and PhoneDisplay properties of the item.
                //The DisplayHeight is done for you.
                 item.DisplayHeight = HeightDisplay(item.Height);
                 item.DisplayCellNbr = PhoneDisplay(item.CellNbr);

            }
            return View(trainees);
        }


        /// <summary>
        /// Return phone number in split phone number display
        /// </summary>
        /// <param name="phoneNumber"></param>
        /// <returns></returns>
        private string PhoneDisplay(string phoneNumber)
        {
            return string.Format("{0}-{1}-{2}", phoneNumber.Substring(0, 3), phoneNumber.Substring(3, 3), phoneNumber.Substring(6, (phoneNumber.Length - 6)));
        }

        //You can create the private methods for HeightDisplay and PhoneDisplay below.
        //The HeightDisplay method signature has been given to you.
        private string HeightDisplay(int height)
        {
            //store the displayed height
            string heightDisplay = "";
            int ft = 0;
            int inch = 0;

            try
            {
                //perform the calculations to separate feet and height (hint: this is a great 
                //time to use the % (modulus) operator
                ft = height / 12;
                inch = height % 12;

                if (inch > 0)
                {
                    heightDisplay = string.Format("{0}ft.{1}in.", ft, inch);
                }
                else
                {
                    heightDisplay = string.Format("{0}ft.", ft);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return heightDisplay;
        }

        public ActionResult WorkOutPlans()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MyswoleMateMvcApp/Controllers/WorkoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyswoleMateMvcApp.Controllers
{
    public class WorkoutController : Controller
    {
        // GET: Workout
        public ActionResult Index()
        {
            return View();
        }
    }
}

MyswoleMateMvcApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<head>
    <title>MySwoleMate</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet"/>
    <link href="~/Content/Site.css" rel="stylesheet"/>
</head>

<body class="index">
    <div id="mainCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#mainCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#mainCarousel" data-slide-to="1"></li>
            <li data-target="#mainCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="Images/gym2.jpg" alt="Gym Image 1" />
                <div class="carousel-caption">
                    <h1 class="title">MySwoleMate</h1>
                    <h1>Your Soul Mate to get SWOLE</h1>
                </div>
            </div>
            <div class="item">
                <img src="Images/gym1.jpg" alt="Gym Image 2" />
                <div class="carousel-caption">
                    <h1>Personal Access to Your Trainees</h1>
                    <p>
                        Instant access to all of your Trainees, with a click of a button!
                    </p>
                    <p>
                        <a href="~/Trainees.aspx"  class="btn btn-lg btn-success">Go To Trainees List</a>
                    </p>
                </div>
            </div>
            <div class="item">
                <img src="Images/weights.jpg" alt="Weight Image 1" />
                <div class="carousel-caption">
                    <h1>Personalized 5-STEP Workout Plan</h1>
                    <p>Create personalized 5-Step Workout Plans for all of your Trainees and assign them to your Trainees! MySwoleMate is is the only app you will need to get your trainees SWOLE.</p>
                    <p>
                        <a href="~/Workout.aspx" class="btn btn-lg btn-success">Create a Workout</a>
                    </p>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#mainCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#mainCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <section class="success">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 text-center">
                    <h2>Personal Access to Your Trainees</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-8 col-xs-offset-2 text-center">
                    <p>
                        Instant access to all of your Trainees, with a click of a button!
                    </p>
                </div>
                <div class="col-xs-8 col-xs-offset-2 text-center">
                    <br />
                    <a href="~/Trainees.aspx" runat="server" class="btn btn-lg btn-outline">Go To Trainees List</a>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-xs-12 text-center">
                    <h2>Personalized 5-Step Workout Plans</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-8 col-xs-offset-2 text-center">
                    <p>Create personalized 5-Step Workout Plans for all of your Trainees and assign them to your Trainees! MySwoleMate is is the only app you will need to get your trainees SWOLE.</p>
                </div>
                <div class="col-xs-8 col-xs-offset-2 text-center">
                    <br />
                    <a href="~/Workout.aspx" runat="server" class="btn btn-lg btn-success">Create a Workout</a>
                </div>
            </div>
        </div>
    </section>
    <section class="success">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 text-center">
                    <h2>Want to know more about us?</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-8 col-xs-offset-2 text-center">
                    <br />
                    <a href="" runat="server" class="btn btn-lg btn-outline">About</a>
                </div>
            </div>
        </div>
    </section>
</body>

MyswoleMateMvcApp/Views/Home/TraineeList.cshtml
@model IEnumerable<MyswoleMateMvcApp.Models.TraineeViewModel>

@{
    ViewBag.Title = "TraineeList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>TraineeList</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TraineeID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Height)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CellNbr)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WorkoutID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DisplayHeight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DisplayCellNbr)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DisplayGender)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TraineeID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Height)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Weight)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CellNbr)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WorkoutID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DisplayHeight)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DisplayCellNbr)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DisplayGender)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

MyswoleMateMvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button  type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Swole Mate", "Index", "Trainee", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right"> <!--aligns these contents to the right-->
                    <li>@Html.ActionLink("Trainee List", "TraineeList", "Trainee")</li>
                    <li>@Html.ActionLink("Work out Plans", "WorkOutPlans", "Trainee")</li>
                    <li>@Html.ActionLink("About", "Contact", "Trainee")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MyswoleMateMvcApp/Views/Trainee/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MyswoleMateMvcApp/Views/Trainee/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyswoleMateMvcApp/Views/Trainee/CreateNewTrainee.cshtml
@model MyswoleMateMvcApp.Models.Trainee

@{
    ViewBag.Title = "CreateNewTrainee";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreateNewTrainee</h2>


@using (Html.BeginForm("CreateNewTraineeInfo", "Trainee", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Trainee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CellNbr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CellNbr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CellNbr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyswoleMateMvcApp/Views/Trainee/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<head>
    <title>MySwoleMate</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet"/>
    <link href="~/Content/Site.css" rel="stylesheet"/>
</head>

<body class="index">
    <div id="mainCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#mainCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#mainCarousel" data-slide-to="1"></li>
            <li data-target="#mainCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="Images/gym2.jpg" alt="Gym Image 1" />
                <div class="carousel-caption">
                    <h1 class="title">MySwoleMate</h1>
                    <h1>Your Soul Mate to get SWOLE</h1>
                </div>
            </div>
            <div class="item">
                <img src="Images/gym1.jpg" alt="Gym Image 2" />
                <div class="carousel-caption">
                    <h1>Personal Access to Your Trainees</h1>
                    <p>
                        Instant access to all of your Trainees, with a click of a button!
                    </p>
                    <p>
                        <a href="~/Trainees.aspx"  class="btn btn-lg btn-success">Go To Trainees List</a>
                    </p>
                </div>
            </div>
            <div class="item">
                <img src="Images/weights.jpg" alt="Weight Image 1" />
                <div class="carousel-caption">
                    <h1>Personalized 5-STEP Workout Plan</h1>
                    <p>Create personalized 5-Step Workout Plans for all of your Trainees and assign them to your Trainees! MySwoleMate is is the only app you will need to get your trainees SWOLE.</p>
                    <p>

                        <a href="~/Workout.aspx" class="btn btn-lg btn-success">Create a Workout</a>
                    </p>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#mainCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#mainCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <section class="success">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 text-center">
                    <h2>Personal Access to Your Trainees</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-8 col-xs-offset-2 text-center">
                    <p>
                        Instant access to all of your Trainees, with a click of a button!
                    </p>
                </div>
                <div class="col-xs-8 col-xs-offset-2 text-center">
                    <br />
                    @Html.ActionLink("Go To Trainee List", "TraineeList", "Home", new { area = "" }, new { @class = "btn btn-lg btn-success" })
                  
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-xs-12 text-center">
                    <h2>Personalized 5-Step Workout Plans</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-8 col-xs-offset-2 text-center">
                    <p>Create personalized 5-Step Workout Plans for all of your Trainees and assign them to your Trainees! MySwoleMate is is the only app you will need to get your trainees SWOLE.</p>
                </div>
                <div class="col-xs-8 col-xs-offset-2 text-center">
                    <br />
                    <a href="~/Workout.aspx" runat="server" class="btn btn-lg btn-success">Create a Workout</a>
                </div>
            </div>
        </div>
    </section>
    <section class="success">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 text-center">
                    <h2>Want to know more about us?</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-8 col-xs-offset-2 text-center">
                    <br />
                    <a href="" runat="server" class="btn btn-lg btn-outline">About</a>
                </div>
            </div>
        </div>
    </section>
</body>

MyswoleMateMvcApp/Views/Trainee/TraineeList.cshtml
@model IEnumerable<MyswoleMateMvcApp.Models.TraineeViewModel>

@{
    ViewBag.Title = "TraineeList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>TraineeList</h2>

<p>
    @Html.ActionLink("Create New Trainee", "CreateNewTrainee")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WorkoutID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DisplayHeight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DisplayCellNbr)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DisplayGender)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
       
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.Weight)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WorkoutID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DisplayHeight)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DisplayCellNbr)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DisplayGender)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>